version: '2'
services:
    ai_projekt-mongodb:
        container_name: ai_projekt-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/AI_projekt/mongodb/:/data/db/
